### ISSUE TITLE
Clipboard and/or RStudio API support

### ISSUE THREAD

**Issue by bryceroney** [tidymodels/usemodels#12]
## Clipboard and/or RStudio API support

I really like the idea behind this package and was thinking the user experience could be improved again by having the code generated also copied to the clipboard (probably using `{clipr}`) and/or using `{rstudioapi}` to insert it into the active document.

I'm not sure if this is an idea that has been canvassed before and rejected, but if there's support I'm happy to take a look at turning my hand to writing it.

**Comment by topepo** [comment]
We'd like to do this but it make take some additional work. I'll look at how `reprex` does this.

**Comment by topepo** [comment]
Done!
