### ISSUE TITLE
code for glmnet_tune does not work

### ISSUE THREAD

**Issue by aloes2512** [tidymodels/usemodels#34]
### Tips for a helpful bug report: 
```glmnet_tune <- 
  tune_grid(glmnet_workflow, resamples = stop("add your rsample object"), grid = glmnet_grid)```
 this code was said to be working after copied to source in R-Studio. But I get an error message:
"       check_rset(resamples) : add your rsample object" 
I don`t know how to solve this as the previous code did not generate an error message.
I am working with a MacBook Air M1 OSx 12.4 and R- Studio: 2022.02.3 Build 492

**Comment by juliasilge** [comment]
Hello @aloes2512! Notice where it says `resamples = stop("add your rsample object")`. This is where you need to add _your_ resamples object; the usemodels output requires you to decide for yourself on the `resamples` and `grid` to use.

You can check out [this blog post and screencast](https://juliasilge.com/blog/ikea-prices/) for a demo of how to do that.
