### ISSUE TITLE
Cubist and C50

### ISSUE THREAD

**Issue by larry77** [tidymodels/usemodels#9]
First things first: this is really great work.
I have not checked up this package in a bit, but if not included already, I would love to see support for Cubist and C50.

**Comment by topepo** [comment]
Cubist has been added. I'll work on C5.0 trees

**Comment by larry77** [comment]
Thanks a lot.

**Comment by topepo** [comment]
Done!

**Comment by larry77** [comment]
Better late than never. Thanks
